[package]
name = "bfcairo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[[target.executable]]

[dependencies]
cairo_execute = "2.10.0"

[dev-dependencies]
cairo_test = "2.10.0"

[cairo]
enable-gas = false